---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nyovape1.
--- DateTime: 2/18/2019 10:14 AM
---


function Utils.appendedFunction(oldFunc, newFunc)
	if oldFunc ~= nil then
		return function (...)
			oldFunc(...);
			newFunc(...);
		end;
	else
		return newFunc;
	end;
end;

function Utils.prependedFunction(oldFunc, newFunc)
	if oldFunc ~= nil then
		return function (...)
			newFunc(...);
			oldFunc(...);
		end;
	else
		return newFunc;
	end;
end;

function Utils.overwrittenFunction(oldFunc, newFunc)
	return function (self, ...)
		return newFunc(self, oldFunc, ...);
	end;
end;